### ISSUE TITLE
OS X 10.12.1 build failure: dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib

### ISSUE THREAD

**Issue by AlmightyOatmeal** [mwilliamson/jq.py#22]
Sad panda... Looks like I'm in the market to find a new JSON query library.

```
$ sudo -H pip install pyjq
Collecting pyjq
  Using cached pyjq-2.0.0.zip
Requirement already satisfied (use --upgrade to upgrade): six in /Library/Python/2.7/site-packages/six-1.10.0-py2.7.egg (from pyjq)
Installing collected packages: pyjq
  Running setup.py install for pyjq ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-mMZOTT/pyjq/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_G2rtW-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.12-intel-2.7
    copying pyjq.py -> build/lib.macosx-10.12-intel-2.7
    running build_ext
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... ./install-sh -c -d
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking for style of include used by make... GNU
    checking dependency style of gcc... gcc3
    checking build system type... i386-apple-darwin16.1.0
    checking host system type... i386-apple-darwin16.1.0
    checking how to print strings... printf
    checking for a sed that does not truncate output... /usr/bin/sed
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for fgrep... /usr/bin/grep -F
    checking for ld used by gcc... /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
    checking if the linker (/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 196608
    checking whether the shell understands some XSI constructs... yes
    checking whether the shell understands "+="... yes
    checking how to convert i386-apple-darwin16.1.0 file names to i386-apple-darwin16.1.0 format... func_convert_file_noop
    checking how to convert i386-apple-darwin16.1.0 file names to toolchain format... func_convert_file_noop
    checking for /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for ar... ar
    checking for archiver @FILE support... no
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for mt... no
    checking if : is a manifest tool... no
    checking for dsymutil... dsymutil
    checking for nmedit... nmedit
    checking for lipo... lipo
    checking for otool... otool
    checking for otool64... no
    checking for -single_module linker flag... yes
    checking for -exported_symbols_list linker flag... yes
    checking for -force_load linker flag... yes
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... yes
    checking for gcc option to produce PIC... -fno-common -DPIC
    checking if gcc PIC flag -fno-common -DPIC works... yes
    checking if gcc static flag -static works... no
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
    checking dynamic linker characteristics... dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
      Referenced from: /usr/local/bin/awk
      Reason: image not found
    LLVM ERROR: IO failure on output stream.
    dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
      Referenced from: /usr/local/bin/awk
      Reason: image not found
    darwin16.1.0 dyld
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... no
    checking whether to build static libraries... yes
    checking whether make sets $(MAKE)... (cached) yes
    checking for ANSI C header files... (cached) yes
    checking for stdlib.h... (cached) yes
    checking for string.h... (cached) yes
    checking for strings.h... (cached) yes
    checking sys/time.h usability... yes
    checking sys/time.h presence... yes
    checking for sys/time.h... yes
    checking for unistd.h... (cached) yes
    checking sys/times.h usability... yes
    checking sys/times.h presence... yes
    checking for sys/times.h... yes
    checking size of int... 4
    checking size of short... 2
    checking size of long... 8
    checking for an ANSI C-conforming const... yes
    checking whether time.h and sys/time.h may both be included... yes
    checking for size_t... yes
    checking for working alloca.h... yes
    checking for alloca... yes
    checking for working memcmp... yes
    checking for prototypes... yes
    checking for variable length prototypes and stdarg.h... yes
    configure: creating ./config.status
    config.status: creating Makefile
    dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
      Referenced from: /usr/local/bin/gawk
      Reason: image not found
    sed: stdout: Broken pipe
    ./config.status: line 1184: 61884 Done(1)                 eval sed \"\$ac_sed_extra\" "$ac_file_inputs"
         61885 Abort trap: 6           | $AWK -f "$ac_tmp/subs.awk" > $ac_tmp/out
    config.status: error: could not create Makefile
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-mMZOTT/pyjq/setup.py", line 116, in <module>
        'Programming Language :: JavaScript',
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 573, in run
        self.run_command('build')
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/tmp/pip-build-mMZOTT/pyjq/setup.py", line 29, in run
        self._build_oniguruma()
      File "/private/tmp/pip-build-mMZOTT/pyjq/setup.py", line 43, in _build_oniguruma
        ["make", "install"],
      File "/private/tmp/pip-build-mMZOTT/pyjq/setup.py", line 70, in _build_lib
        subprocess.check_call(command, cwd=lib_dir)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['./configure', 'CFLAGS=-fPIC', '--disable-shared', '--prefix', '/private/tmp/pip-build-mMZOTT/pyjq/dependencies/onig_install']' returned non-zero exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-mMZOTT/pyjq/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_G2rtW-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-mMZOTT/pyjq/
```

```
$ ls -lh /usr/local/opt/readline/lib/libreadline*
-r--r--r--  1 jamie  admin   449K Oct  7 22:48 /usr/local/opt/readline/lib/libreadline.7.0.dylib
lrwxr-xr-x  1 jamie  admin    21B Sep  7 16:16 /usr/local/opt/readline/lib/libreadline.7.dylib -> libreadline.7.0.dylib
-r--r--r--  1 jamie  admin   734K Sep  7 16:16 /usr/local/opt/readline/lib/libreadline.a
lrwxr-xr-x  1 jamie  admin    21B Sep  7 16:16 /usr/local/opt/readline/lib/libreadline.dylib -> libreadline.7.0.dylib
```

```
$ brew install autoconf automake libtool
Warning: autoconf-2.69 already installed
Warning: automake-1.15 already installed
Warning: libtool-2.4.6_1 already installed
```

```
$ brew install readline
Warning: readline-7.0 already installed
```

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.1
BuildVersion:	16B2338c
```

**Comment by mwilliamson** [comment]
This is the repository for the PyPI package `jq`, not `pyjq`: I think you need to file an issue somewhere else!

**Comment by AlmightyOatmeal** [comment]
Really? Because that is the pypi package associated with this project...

**Comment by mwilliamson** [comment]
When I look at the project on PyPI [1], it links to another GitHub
repository [2], not this one.

[1] https://pypi.python.org/pypi/pyjq
[2] http://github.com/doloopwhile/pyjq

**Comment by AlmightyOatmeal** [comment]
You are correct, that was my mistake. I had too many tabs open in my browser and it was a slip on my part for sure.
