### ISSUE TITLE
unable to install on mac via pip

### ISSUE THREAD

**Issue by shdobxr** [mwilliamson/jq.py#31]
`uname 
Darwin 88e9fe73e507 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64`

`pip install jq                                                                                                                                                                         
Collecting jq
  Using cached https://files.pythonhosted.org/packages/82/0c/bf3f544f850cef19f4468bea93e4d0aa908e0d8c601609ba1ed561b42c79/jq-0.1.6.tar.gz
Building wheels for collected packages: jq
  Running setup.py bdist_wheel for jq ... error
  Complete output from command /usr/local/opt/python@2/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/4y/ld4t0qxn3tn9t1h_y4_rkg340000gp/T/pip-install-KcSdd0/jq/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/4y/ld4t0qxn3tn9t1h_y4_rkg340000gp/T/pip-wheel-rHZOrb --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/4y/ld4t0qxn3tn9t1h_y4_rkg340000gp/T/pip-install-KcSdd0/jq/setup.py", line 123, in <module>
      'Programming Language :: Python :: 3.5',
    File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 143, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/private/var/folders/4y/ld4t0qxn3tn9t1h_y4_rkg340000gp/T/pip-install-KcSdd0/jq/setup.py", line 40, in run
      self._build_oniguruma()
    File "/private/var/folders/4y/ld4t0qxn3tn9t1h_y4_rkg340000gp/T/pip-install-KcSdd0/jq/setup.py", line 52, in _build_oniguruma
      ["make", "install"],
    File "/private/var/folders/4y/ld4t0qxn3tn9t1h_y4_rkg340000gp/T/pip-install-KcSdd0/jq/setup.py", line 68, in _build_lib
      self._download_tarball(source_url, tarball_path)
    File "/private/var/folders/4y/ld4t0qxn3tn9t1h_y4_rkg340000gp/T/pip-install-KcSdd0/jq/setup.py", line 88, in _download_tarball
      tarfile.open(tarball_path, "r:gz").extractall(path_in_dir("."))
    File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1693, in open
      return func(name, filemode, fileobj, **kwargs)
    File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1751, in gzopen
      raise ReadError("not a gzip file")
  tarfile.ReadError: not a gzip file

  ----------------------------------------
  Failed building wheel for jq
  Running setup.py clean for jq
Failed to build jq
Installing collected packages: jq
  Running setup.py install for jq ... error
    Complete output from command /usr/local/opt/python@2/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/4y/ld4t0qxn3tn9t1h_y4_rkg340000gp/T/pip-install-KcSdd0/jq/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/4y/ld4t0qxn3tn9t1h_y4_rkg340000gp/T/pip-record-pegN44/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4y/ld4t0qxn3tn9t1h_y4_rkg340000gp/T/pip-install-KcSdd0/jq/setup.py", line 123, in <module>
        'Programming Language :: Python :: 3.5',
      File "/usr/local/lib/python2.7/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/4y/ld4t0qxn3tn9t1h_y4_rkg340000gp/T/pip-install-KcSdd0/jq/setup.py", line 40, in run
        self._build_oniguruma()
      File "/private/var/folders/4y/ld4t0qxn3tn9t1h_y4_rkg340000gp/T/pip-install-KcSdd0/jq/setup.py", line 52, in _build_oniguruma
        ["make", "install"],
      File "/private/var/folders/4y/ld4t0qxn3tn9t1h_y4_rkg340000gp/T/pip-install-KcSdd0/jq/setup.py", line 68, in _build_lib
        self._download_tarball(source_url, tarball_path)
      File "/private/var/folders/4y/ld4t0qxn3tn9t1h_y4_rkg340000gp/T/pip-install-KcSdd0/jq/setup.py", line 88, in _download_tarball
        tarfile.open(tarball_path, "r:gz").extractall(path_in_dir("."))
      File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1693, in open
        return func(name, filemode, fileobj, **kwargs)
      File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1751, in gzopen
        raise ReadError("not a gzip file")
    tarfile.ReadError: not a gzip file

    ----------------------------------------
Command "/usr/local/opt/python@2/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/4y/ld4t0qxn3tn9t1h_y4_rkg340000gp/T/pip-install-KcSdd0/jq/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/4y/ld4t0qxn3tn9t1h_y4_rkg340000gp/T/pip-record-pegN44/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/4y/ld4t0qxn3tn9t1h_y4_rkg340000gp/T/pip-install-KcSdd0/jq/`

**Comment by mwilliamson** [comment]
I've added support for wheels on Linux and Mac OS X in the latest version. Hopefully they work for you, but shout if not!
