### ISSUE TITLE
OS X install fails: ./libtool: eval: line 1720: syntax error near unexpected token `|'

### ISSUE THREAD

**Issue by techandtools** [mwilliamson/jq.py#37]
I'm installing JQ using "pip3 install jq" on macOS (Mojave 10.14.6). I installed the latest version of XCODE, ran a full "brew upgrade" and "brew install autoconf automake libtool". Every time installation fails with the exact same issue (see output snippet below).

Any help on what might be causing this is very appreciated.

```
   checking for tan... yes
    checking for tanh... yes
    checking for tgamma... yes
    checking for y0... yes
    checking for y1... yes
    checking for pow... yes
    checking for atan2... yes
    checking for hypot... yes
    checking for remainder... yes
    checking for thread-local storage... no
    checking whether byte ordering is bigendian... no
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: executing depfiles commands
    config.status: executing libtool commands
    Executing: make
    /Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
      GEN      version.h
      CC       main.o
      CC       locfile.lo
      CC       bytecode.lo
      CC       compile.lo
      CC       execute.lo
      CC       builtin.lo
      CC       jv.lo
      CC       jv_parse.lo
      CC       jv_print.lo
      CC       jv_dtoa.lo
      CC       jv_unicode.lo
      CC       jv_aux.lo
      CC       jv_file.lo
      CC       jv_alloc.lo
      CC       jq_test.lo
      CC       util.lo
      CC       linker.lo
      CC       parser.lo
      CC       lexer.lo
      CCLD     libjq.la
    ./libtool: eval: line 1720: syntax error near unexpected token `|'
    ./libtool: eval: line 1720: `/usr/bin/nm -B  .libs/locfile.o .libs/bytecode.o .libs/compile.o .libs/execute.o .libs/builtin.o .libs/jv.o .libs/jv_parse.o .libs/jv_print.o .libs/jv_dtoa.o .libs/jv_unicode.o .libs/jv_aux.o .libs/jv_file.o .libs/jv_alloc.o .libs/jq_test.o .libs/util.o .libs/linker.o .libs/parser.o .libs/lexer.o   |  | /usr/bin/sed 's/.* //' | sort | uniq > .libs/libjq.exp'
    make[1]: *** [libjq.la] Error 1
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_m/9k2by9n51ydb8t7wj33h82sh0000gn/T/pip-req-build-p127ofik/setup.py", line 123, in <module>
        'Programming Language :: Python :: 3.5',
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/_m/9k2by9n51ydb8t7wj33h82sh0000gn/T/pip-req-build-p127ofik/setup.py", line 41, in run
        self._build_libjq()
      File "/private/var/folders/_m/9k2by9n51ydb8t7wj33h82sh0000gn/T/pip-req-build-p127ofik/setup.py", line 64, in _build_libjq
        ["make"],
      File "/private/var/folders/_m/9k2by9n51ydb8t7wj33h82sh0000gn/T/pip-req-build-p127ofik/setup.py", line 79, in _build_lib
        run_command(command)
      File "/private/var/folders/_m/9k2by9n51ydb8t7wj33h82sh0000gn/T/pip-req-build-p127ofik/setup.py", line 76, in run_command
        subprocess.check_call(args, cwd=lib_dir)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/_m/9k2by9n51ydb8t7wj33h82sh0000gn/T/pip-req-build-p127ofik/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/_m/9k2by9n51ydb8t7wj33h82sh0000gn/T/pip-record-qju8leis/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/_m/9k2by9n51ydb8t7wj33h82sh0000gn/T/pip-req-build-p127ofik/
```

**Comment by mwilliamson** [comment]
I've added support for wheels on Linux and Mac OS X in the latest version. Hopefully they work for you, but shout if not!
