### ISSUE TITLE
fails with python 3.8

### ISSUE THREAD

**Issue by yhager** [mwilliamson/jq.py#40]
On a clean venv, running the first example from the documentation fails:
```
$ python -m venv jq
$ jq/bin/pip install jq
Collecting jq
  Using cached https://files.pythonhosted.org/packages/82/0c/bf3f544f850cef19f4468bea93e4d0aa908e0d8c601609ba1ed561b42c79/jq-0.1.6.tar.gz
Installing collected packages: jq
  Running setup.py install for jq ... done
Successfully installed jq-0.1.6
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$ jq/bin/python
Python 3.8.0 (default, Oct 23 2019, 18:51:26) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from jq import jq
>>> jq(".").transform("42") == "42"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "jq.pyx", line 131, in jq._Program.transform (jq.c:1925)
TypeError: 'cython_function_or_method' object does not support vectorcall
>>> 
```

**Comment by mwilliamson** [comment]
Python 3.8 should be supported in the latest version, 0.1.7. Could you give it a try?

**Comment by yhager** [comment]
Yes, 0.1.7 works with the above example. Thanks!
