### ISSUE TITLE
cmath functions not available

### ISSUE THREAD

**Issue by statmatt** [mwilliamson/jq.py#72]
This may be user-error, but attempts to compile statements with cmath operators are causing compilation errors showing they're not available:

```jq.compile(".[] | pow(.x, 2)").input([{'x': 2}]).all()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "jq.pyx", line 124, in jq.compile
  File "jq.pyx", line 236, in jq._Program.__cinit__
  File "jq.pyx", line 207, in jq._JqStatePool.__cinit__
  File "jq.pyx", line 158, in jq._compile
  File "jq.pyx", line 141, in jq._compile
  File "jq.pyx", line 152, in jq._compile
ValueError: jq: error: pow/1 is not defined at <top-level>, line 1:
.[] | pow(.x, 2)      
jq: 1 compile error
jq.compile(".[] | sin(.x)").input([{'x': 2}]).all()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "jq.pyx", line 124, in jq.compile
  File "jq.pyx", line 236, in jq._Program.__cinit__
  File "jq.pyx", line 207, in jq._JqStatePool.__cinit__
  File "jq.pyx", line 158, in jq._compile
  File "jq.pyx", line 141, in jq._compile
  File "jq.pyx", line 152, in jq._compile
ValueError: jq: error: sin/1 is not defined at <top-level>, line 1:
.[] | sin(.x)      
jq: 1 compile error
```

If these are not available, can we please fix this to have linking so that math functions are correctly available as described https://stedolan.github.io/jq/manual/v1.5/#Math ?

**Comment by mwilliamson** [comment]
I don't think that's the right usage -- I believe pow is a two argument function, while sin is a zero argument function:

```
>>> jq.compile(".[] | pow(.x; 2)").input([{'x': 2}]).all()
[4]
>>> jq.compile(".[].x | sin").input([{'x': 2}]).all()
[0.9092974268256817]
```

**Comment by statmatt** [comment]
perfect, I knew this was probably a user error, thank you for clarifying.
